# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 08:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import drops.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtPiece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, unique=True)),
                ('preview_image', models.ImageField(default='stock/stealth_drop.png', upload_to=drops.models.user_uploads)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.CharField(max_length=36, null=True)),
                ('trimmed_uuid', models.CharField(max_length=8, null=True)),
                ('status', models.CharField(choices=[('Ready to Drop', 'Ready to Drop'), ('Dropped!', 'Dropped!')], default='Ready to Drop', max_length=11)),
                ('url_slug', models.SlugField()),
                ('likes', models.IntegerField(default=0)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artpiece', to='locations.City')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
