# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 16:04
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riddle', models.TextField()),
                ('gps_coords', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('artpiece', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='drops.ArtPiece')),
            ],
        ),
    ]
