# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 01:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artpiece',
            name='trimmed_uuid',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='artpiece',
            name='uuid',
            field=models.CharField(max_length=36, null=True),
        ),
    ]
