# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drops', '0003_auto_20171019_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='artpiece',
            name='status',
            field=models.CharField(choices=[('Ready to Drop', 'Ready to Drop'), ('Dropped!', 'Dropped!')], default='Ready to Drop', max_length=11),
        ),
    ]
