# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 02:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drops', '0004_artpiece_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artpiece',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artpiece', to='locations.City'),
        ),
        migrations.AlterField(
            model_name='artpiece',
            name='url_slug',
            field=models.SlugField(),
        ),
    ]
