# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drops', '0005_auto_20171105_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artpiece',
            name='status',
            field=models.CharField(choices=[('Ready to Drop', 'Ready to Drop'), ('Dropped!', 'Dropped!')], default='Ready to Drop', max_length=13),
        ),
    ]
