# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 03:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import drops.models


class Migration(migrations.Migration):

    dependencies = [
        ('drops', '0005_auto_20171025_0251'),
    ]

    operations = [
        migrations.AddField(
            model_name='artpiece',
            name='preview_image',
            field=models.ImageField(default='stock/stealth_drop.png', upload_to=drops.models.user_uploads),
        ),
        migrations.AlterField(
            model_name='artpiece',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
