# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 17:19
from __future__ import unicode_literals

from django.db import migrations, models
import drops.models


class Migration(migrations.Migration):

    dependencies = [
        ('drops', '0006_auto_20171105_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artpiece',
            name='uuid',
            field=models.CharField(default=drops.models.create_uuid, max_length=36),
        ),
    ]
