# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 04:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drops', '0006_artpiece_preview_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artpiece',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
