# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drops', '0007_auto_20171105_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artpiece',
            name='trimmed_uuid',
            field=models.CharField(blank=True, default='', max_length=8),
            preserve_default=False,
        ),
    ]
