# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 18:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drops', '0008_auto_20171105_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artpiece',
            name='trimmed_uuid',
        ),
    ]
