# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 04:47
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drops', '0009_remove_artpiece_trimmed_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hint',
            name='gps_coords',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
