# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 02:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=20)),
                ('city_latitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('city_longitude', models.DecimalField(decimal_places=8, max_digits=11)),
            ],
            options={
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=20)),
                ('country_latitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('country_longitude', models.DecimalField(decimal_places=8, max_digits=11)),
            ],
            options={
                'verbose_name_plural': 'Counrties',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=20)),
                ('state_latitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('state_longitude', models.DecimalField(decimal_places=8, max_digits=11)),
            ],
            options={
                'verbose_name_plural': 'States',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country', to='locations.Country'),
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city', to='locations.State'),
        ),
    ]
