# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 03:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20171018_0249'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['-country'], 'verbose_name_plural': 'Cities'},
        ),
    ]
