# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 08:00
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HintStation',
            fields=[
                ('station_name', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('station_coordinates', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('activation_status', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('visitor_count', models.IntegerField(default=0)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station', to='locations.City')),
            ],
            options={
                'verbose_name_plural': 'Hint Stations',
            },
        ),
    ]
