# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 03:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0003_auto_20171018_0320'),
    ]

    operations = [
        migrations.CreateModel(
            name='HintStation',
            fields=[
                ('station_name', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('station_longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('activation_status', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('visitor_count', models.IntegerField(default=0)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station', to='locations.City')),
            ],
            options={
                'verbose_name_plural': 'Hint Stations',
            },
        ),
    ]
