# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hintstation',
            name='station_latitude',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=11),
            preserve_default=False,
        ),
    ]
